services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: smart-claims-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./configs:/app/configs

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: smart-claims-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped
